# Per-client facts for the Benefit Data Processor documentation.
# Sources: DataProcesser/Clients/* (branch jira/ABE-5177-…-hanback-report @ 2026-09-21), live AWS inventory
# (ap-southeast-1, 2026-09-21), docs/data-processor/*, and the project memory notes.

ENV_DB = {
    "PROD": "secret benefit-connection-string-preprod → connectionStringBenefitProduction",
    "PREPROD": "secret benefit-connection-string-preprod → connectionStringBenefitPreProd (Aurora preprod-20270707 is STOPPED)",
    "UAT": "secret benefit-connection-string-preprod → connectionStringBenefitUat (AspireProdBackup on the benefit-sit cluster)",
}

# pipeline rows: (env, entry, landing, rule (state), queue, jobdef, image, target)
CLIENTS = [
dict(code="AEO", name="AEON (Thailand)", jobtype="CLIENT_AEO_DATA_PROCESSER", folder="Clients/AEON", cls="AEOBatchProcessor",
  files="AEOBatchProcessor.cs, AEOConstants.cs, AeonCustomerAttribute.cs, FixedLengthColumn.cs, MultiThreadedCustomerHandler.cs", loc=733,
  trigger="SFTP pull → S3 drop", kind="sftp-s3",
  pipeline=[
   ("PROD","Scheduler benefit-pull-file-sftp-aeon-data-production → Lambda common-benefit-lambda-pullfile-sftp-production","s3://aspire-internal-app/production/clients/aeon/","benefit-import-data-clients-aeo-prod (ENABLED)","benefit-import-aeon-production-job-queue","benefit-aeon-import-production-job-definitions:4 (revision-pinned)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("PREPROD","(no pull; manual drop)","s3://aspire-internal-app/preprod/clients/aeon/","benefit-import-data-clients-aeo-preprod (ENABLED)","benefit-import-aeon-preprod-job-queue","benefit-aeon-import-preprod-job-definitions:3 (by name)","apac-benefit-data-processer-pre-production (untagged)","PREPROD — DB stopped"),
   ("UAT","QA test-drop tool / manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-aeo-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Zip from SFTP containing fixed-length member files; member file prefix <code>ROPWLD_</code> (FixedLengthColumn.cs defines the column offsets). Per the AEON/CHUBB SFTP guide the SFTP payload is PGP-encrypted and decrypted by the pull-file Lambda before landing.",
  reader="Fixed-width text via FixedLengthColumn; MultiThreadedCustomerHandler upserts in parallel batches.",
  password="—", uuid="Configured in client_customer_field_config (no DefaultFieldConfigs in code)",
  mapping="Attribute JSON via AeonCustomerAttribute; validation from client_customer_field_config (LoadFieldConfigs)",
  programs="ProgramNumber <code>285SSC796715</code> (was PROGRAM_CODE <code>AEON-285SSC796715</code>); same in UAT and PROD. Resolved via ProgramTierLookup, legacy lookup kept as logged fallback.",
  report="Yes since ABE-5152 (sprint 70): HandbackRowCollector rows Inserted/Updated/SameData/Invalid/DuplicateUUID with Row No; broken zip / missing member file now = Failed run with reason (previously silent 'No valid data').",
  deploy="Prod rule pins a revision → register new revision of benefit-aeon-import-production-job-definitions AND repoint benefit-import-data-clients-aeo-prod. Preprod rule references by name.",
  test=["UAT: submit benefit-aeo-import-uat-job-definitions on benefit-import-uat-job-queue with S3_BUCKET_NAME/S3_OBJECT_KEY pointing at a zip under aspire-internal-app (or extend the test-drop tool — AEO is not wired in it yet).","Preprod: copy an existing object to a new key under preprod/clients/aeon/ to fire the rule (DB is stopped, so the job will fail on MySQL connect — UAT only).","Check the run in ABF Data Processor Report on benefit-uat (folder AEO/UAT/)."],
  gotchas=["Scheduler benefit-production-import-customer-aeon is DISABLED — the S3 rule is the only prod trigger.","Legacy processor: no DefaultFieldConfigs in code, so an empty client_customer_field_config for AEO means no validation at all."],
  open=["Add AEO to the QA test-drop tool (sprint-70 session in progress)."],
  jira="ABE-5152 (report + ProgramNumber), epic ABE-5148", docs="docs/data-processor/AD-SFTP- Overview - Retrieving Customer Data via PGP encryption file - AEON - CHUBB.pdf, AD-SCB - SCB CardX - AEON.pdf"),

dict(code="AOI", name="Aioi Bangkok Insurance", jobtype="CLIENT_AOI_DATA_PROCESSER", folder="Clients/AOI", cls="AOIBatchProcessor",
  files="AOIBatchProcessor.cs, AOIConstanst.cs, AOIModel.cs, ProcessFile.cs", loc=1591, trigger="SFTP (Transfer Family) drop → S3", kind="sftp-s3",
  pipeline=[
   ("PROD","Client uploads to SFTP (Transfer Family bucket)","s3://sftp-aspirelifestylesasia-com/aioi/aioi_prod/aioi_prod/","aoi-client-import-data-prod-rule (ENABLED)","aoi-client-import-data-queue-prod","aoi-import-data-client-prod-job-definition:9 (by name)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("UAT","QA test-drop tool submits the job (rule DISABLED)","s3://sftp-aspirelifestylesasia-com/aioi/aioi_development/aioi_development/","aoi-client-import-data-uat-rule (DISABLED)","aoi-client-import-data-queue-uat","aoi-import-data-client-uat-job-definition:13 (by name)","aoi-client-uat-import-data:latest (OWN ECR repo)","not set in job def — test-drop passes CONNECTION_TARGET=UAT"),
  ],
  fmt="PGP-encrypted delimited text file (ProcessFile.cs decrypts, then parses).", reader="DecryptPgpAsync + line parser.", password="PGP private key from Secrets Manager (see Common/DecryptPgpAsync.cs)",
  uuid="From client_customer_field_config", mapping="Validation from client_customer_field_config",
  programs="ProgramNumber <code>AIOI00001</code> → UAT program 672 / tier 2171. Prod verified via the same number.",
  report="Yes (HandbackBatchProcessorBase, enableHandback:true) since ABE-5151 (AOI/MIT handbook report PR #3690).",
  deploy="UAT: push <code>aoi-client-uat-import-data:latest</code> — no job-def revision needed (tag is :latest). PROD: shared production image, job def by name → register new revision.",
  test=["Use the QA test-drop tool (kind AOI): it drops the file under aioi_development and submits the job with CONNECTION_TARGET=UAT.","Verify in ABF Data Processor Report on benefit-uat — AOI client 347 exists only on UAT, not SIT."],
  gotchas=["UAT job def sets ENV=UAT which the code never reads; without CONNECTION_TARGET=UAT it resolves LOCAL and tries 127.0.0.1 from Fargate.","Report can only be verified on benefit-uat; SIT has no AOI client row."],
  open=[], jira="ABE-5151, ABE-5157", docs="—"),

dict(code="CHU", name="Chubb (Kids Privilege)", jobtype="CLIENT_CHU_DATA_PROCESSER", folder="Clients/CHU", cls="CHUBatchProcessor",
  files="CHUBatchProcessor.cs, CHUConstants.cs, CHUCustomerRequest.cs, MultiThreadedCustomerHandler.cs", loc=812, trigger="SFTP pull → S3 drop", kind="sftp-s3",
  pipeline=[
   ("PROD","Scheduler benefit-pull-file-sftp-chubb-data-production → Lambda common-benefit-lambda-pullfile-sftp-production","s3://aspire-internal-app/production/clients/chubb/","benefit-import-data-clients-chubb-prod (ENABLED)","benefit-import-chubb-production-job-queue","benefit-chubb-import-production-job-definitions:7 (revision-pinned)","apac-benefit-data-processer-production:v1.1","PROD"),
   ("PREPROD","manual drop (pull schedule DISABLED)","s3://aspire-internal-app/preprod/clients/chubb/","benefit-import-data-clients-chubb-preprod (ENABLED)","benefit-import-chubb-preprod-job-queue","benefit-chubb-import-preprod-job-definitions:8 (revision-pinned)","apac-benefit-data-processer-pre-production (untagged)","PREPROD — DB stopped"),
   ("UAT","QA test-drop tool / manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-chu-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Excel <code>BENEFIT_DATA_CHUBB_ddMMyyyy.xlsx</code> (example in preprod: BENEFIT_DATA_CHUBB_27022026.xlsx). PGP on the SFTP leg per the AEON/CHUBB guide.",
  reader="Excel via ExcelDataReader; MultiThreadedCustomerHandler.", password="—", uuid="From client_customer_field_config", mapping="Validation from client_customer_field_config",
  programs="ProgramNumber <code>285MTT1066373</code>, tier <code>Chubb Kids Privilege Customers</code> (program 122 in PROD). Same number in both envs. <strong>Behaviour change ABE-5153:</strong> the import never assigned a program before (PROD: 114 of 117 imported customers had none); it now attaches the program on insert and to touched customers lacking it, using the program's dates.",
  report="Yes since ABE-5153 (sprint 70).",
  deploy="Both prod and preprod rules pin a revision → register revision + repoint rule.",
  test=["UAT: manual submit of benefit-chu-import-uat-job-definitions with S3_BUCKET_NAME/S3_OBJECT_KEY of an xlsx (test-drop wiring pending).","Preprod: copy BENEFIT_DATA_CHUBB_*.xlsx to a new key under preprod/clients/chubb/ (DB stopped — for rule/plumbing checks only)."],
  gotchas=["Scheduler benefit-production-import-customer-chubb and benefit-preprod-import-customer-chubb are DISABLED; the S3 rule is the trigger.","The program-assignment change needs BA confirmation before prod release (it back-fills touched customers)."],
  open=["BA confirmation of the ABE-5153 program back-fill behaviour.","Add CHU to the test-drop tool."],
  jira="ABE-5153, epic ABE-5148", docs="AD-SFTP- Overview … AEON - CHUBB.pdf"),

dict(code="CSM", name="Chubb Samaggi (Motor / A&H)", jobtype="CLIENT_CSM_DATA_PROCESSER", folder="Clients/CSM", cls="CSMBatchProcessor",
  files="CSMBatchProcessor.cs, CSMConstants.cs, CSMModels.cs, CSMProcessFile.cs, CSMRowValidator.cs", loc=1214, trigger="SFTP folder → queue row → Batch", kind="queue-row",
  pipeline=[
   ("UAT","QA test-drop tool writes the file + PENDING_INSERT row and submits by NAME (no EventBridge rule)","s3://sftp-aspirelifestylesasia-com/chubb/chubb_uat/{CHUBB_AH|CHUBB_MOTOR}/","— (none)","benefit-import-uat-job-queue","benefit-csm-import-uat-job-definitions:6 (by name)","apac-benefit-data-processer-pre-production:uat-abe5384-csm-20260917-01","UAT"),
   ("PROD","not built yet","—","—","—","—","—","—"),
  ],
  fmt="CSV; the processor looks in every client folder (CHUBB_AH and CHUBB_MOTOR) before calling a run empty.", reader="CSMProcessFile + CSMRowValidator (PackageType ENUM Silver/Gold/Copper/Legacy; Motor feed accepts only Silver/Gold).",
  password="—", uuid="PolicyNumber (config)", mapping="RegistrationDate, FirstNameEN, LastNameEN, CarBrand, CarModel, CarYear, CarColor, ChassisNumber, LicenseNumber, RegistrationProvince→AddressEN (also written to the core AddressEn column), PolicyNumber, EffectiveDate, ExpirationDate, CancellationDate, VehicleCode, CCCar, Reference1, Reference2, MemberStatus, PackageType, Channel",
  programs="ProgramNumber <code>2851134436</code>, tier <code>Chubb Samaggi (Motor Group)</code>.",
  report="Yes (HandbackBatchProcessorBase). Queue rows are claimed atomically and drained in order so parallel jobs cannot double-import (e1e44afcd).",
  deploy="UAT: copy latest revision's containerProperties, swap the image, register — the tool submits by name so no rule to repoint. Prod needs job def + rule + SFTP bridge (not yet created).",
  test=["Test-drop tool → CSM (choose AH or MOTOR folder).","UAT masterdata gotcha: the Customer_Attribute_DataType parent row has a non-NULL ParentId — resolve ENUM by MasterCode join, never `ParentId IS NULL`. UAT ENUM id = 50598."],
  gotchas=["Prod release needs database/Sprint63/ABE-5384_CSM_PackageType_enum.sql.","Merged to data-processer-production via PR #3710 but no prod infra exists yet."],
  open=["Prod SFTP bridge, job def and rule.","Prod SQL for PackageType enum."], jira="ABE-5384", docs="issues/ABE-5384-CSM-questions.md"),

dict(code="FWD", name="FWD Insurance (sub-clients FWU / FWS / FWW / FWT)", jobtype="CLIENT_FWD_DATA_PROCESSER", folder="Clients/FWD", cls="FWDBatchProcessor",
  files="FWDBatchProcessor.cs, FWDConstants.cs, FWDEmailTemplate.cs, FWDModels.cs, FWDProcessFile.cs", loc=1729, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES PROD-EMAIL-FWD ← fwd-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/FWDDataProcessor/","fwd-prod-email-rule (ENABLED)","benefit-fwd-import-customer-job-queue-prod","benefit-fwd-import-prod-job-definitions:5 (revision-pinned)","apac-benefit-data-processer-production:fwd-abe5325-20260909","PROD"),
   ("UAT","SES uat-EMAIL-FWD ← fwd-uat-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/uat/EMAIL/FWDDataProcessor/","fwd-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-fwd-import-uat-job-definitions:6 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5325-fwd-20260908-01","UAT"),
  ],
  fmt="Excel attachment (xlsx, sometimes zipped) — one file per sub-client (templates FWD.xlsx / FWT.xlsx / FWW.xlsx in docs).", reader="MimeKit → attachment → Excel; S3_OBJECT_KEY = the triggering mail.",
  password="—", uuid="Composite: FirstNameEN + LastNameEN + CardType + InsuredID + EffectiveDate + ExpirationDate (FWU/FWW); FWT drops InsuredID/dates; FWS adds ProductName (BuildUUIDForFWUFWW).",
  mapping="MemRefId→ReferenceID, FirstNameEN, LastNameEN, InsuredID, ProductName, Plan→PlanCode, PayerN→PayerFname, PayerLN→PayerLname, CustAddress→Address, DateOfBirth→CusBirth, MoblieNo→Phone, EmailAddress, EligibleRound, DtPlanStart→EffectiveDate, DtPlanEnd→ExpirationDate. Client ids: default 375, FWT 336.",
  programs="Per sub-client program lookup (not yet on ProgramNumber — not in the sprint-70 scope).",
  report="Yes.", deploy="Both rules pin a revision → register + repoint. Prod tag convention fwd-&lt;ticket&gt;-&lt;date&gt;.",
  test=["Send a NEW email (not a reply) with the xlsx to fwd-uat-import@… or use the test-drop tool (kind email).","Duplicate-prevention check: hold GET_LOCK('abcb_fwd_data_processor') externally and confirm the job waits (140 s vs ~35 s normal)."],
  gotchas=["2026-08-18 incident: two overlapping runs (V0/V1 of the same file) inserted 2,117 duplicate FWW customers — dedup snapshot is loaded once at transaction start and no unique index exists.","ABE-5325 fix (advisory lock + UUID normalisation) is deployed to UAT and prod (fwd-abe5325-20260909); the 600 s lock timeout rejects a second file instead of queueing it and that path publishes no handback row.","Excel date cells: use CommonDate.TryParseDateCell — the culture round-trip bug was first found here.","Duplicates are byte-identical; diagnose by CreatedOn + run overlap, not by data diff."],
  open=["Clean-up of the 2,117 duplicate FWW rows (+ their customerprograms).","Unique index on the UUID components."], jira="ABE-5325, ABE-5142", docs="docs/data-processor/FWD.xlsx, FWT.xlsx, FWW.xlsx; issues/FWW-duplicate-customers-2026-08-18.md"),

dict(code="HOG", name="Harley-Davidson (Power Station Motosport Co., Ltd.)", jobtype="CLIENT_HOG_DATA_PROCESSER", folder="Clients/HOG", cls="HOGBatchProcessor",
  files="HOGBatchProcessor.cs, HOGConstants.cs, HOGModel.cs, HOGProcessFile.cs", loc=1385, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-Harley ← harley-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/Harley/","harley-prod-email-rule (ENABLED)","benefit-import-harley-prod-job-queue","benefit-harley-import-prod-job-definitions:6 (by name)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("UAT","SES uat-EMAIL-Harley ← harley-uat-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/uat/EMAIL/Harley/","hog-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-hog-import-uat-job-definitions:7 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5149-5150-5154-20260811-04","UAT"),
  ],
  fmt="Excel attachment (xlsx / zipped xlsx).", reader="MimeKit → Excel. Reads the triggering email since ABE-5149 (was newest-in-prefix).", password="—",
  uuid="From client_customer_field_config", mapping="Validation from client_customer_field_config",
  programs="Legacy lookup (not in the sprint-70 ProgramNumber scope).", report="Yes — retrofitted in ABE-5149/5150/5154 (Aug 2026); 'No attachment found in the email.' now publishes a Failed run.",
  deploy="PROD job def referenced by name (new revision deploys); UAT rule pins a revision → repoint.",
  test=["Send a NEW email to harley-uat-import@… or use the test-drop tool (kind email).","Mail five scenarios at once and check each produces its own run folder (conditional-write folder claim)."],
  gotchas=["Reply-chain emails hide the attachment in the quoted part → 'no attachment' branch.","Prod image is still v1.0 (Feb-era) while UAT runs the Aug-2026 report build — prod has not received the report retrofit."],
  open=["Promote the ABE-5149/5150/5154 build to prod."], jira="ABE-5149, ABE-5150, ABE-5154", docs="AD-Honda-TYT-Harley-MIT.pdf"),

dict(code="HOT", name="Honda", jobtype="CLIENT_HOT_DATA_PROCESSER", folder="Clients/HOT", cls="HOTBatchProcessor",
  files="HOTBatchProcessor.cs, HOTModel.cs, HOTProcesserFile.cs, HondaConstanst.cs", loc=1251, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-Honda ← honda-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/Honda/","honda-prod-email-rule (ENABLED)","benefit-import-honda-prod-job-queue","benefit-honda-import-prod-job-definitions:9 (revision-pinned)","apac-benefit-data-processer-production:honda-20260702-1","PROD"),
   ("UAT","SES uat-EMAIL-Honda ← honda-uat-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/uat/EMAIL/Honda/","hot-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-hot-import-uat-job-definitions:7 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5149-5150-5154-20260811-04","UAT"),
  ],
  fmt="Excel 'Honda Loading' xlsx (sample docs/data-processor/Honda Loading_202604101.xlsx), ~37k rows per file.", reader="HOTProcesserFile.ReadHondaCustomersFromXlsx; dates via CommonDate.TryParseDateCell since ABE-4983.",
  password="—", uuid="ChassisNumber (only mandatory field, client_customer_field_config ClientID 38)", mapping="HondaConstanst.ValidateByFieldConfigsHonda",
  programs="Legacy lookup.", report="Yes (Aug 2026 retrofit).",
  deploy="Both rules pin a revision → register + repoint. Prod tag honda-&lt;date&gt;-n.",
  test=["Local, DB-free: uncomment HOTLocalTest.RunValidationTest() / RunDateAccuracyTest() in Program.cs.","UAT: new email to honda-uat-import@… or test-drop tool."],
  gotchas=["ABE-4983: reading date cells with ToString() under InvariantCulture produced MM/dd → 75% rows rejected and survivors day/month-swapped. Never cell.ToString() a date.","Blank Plate/CarColor are not errors — only ChassisNumber is mandatory."],
  open=[], jira="ABE-4983, ABE-5149", docs="AD-Honda-TYT-Harley-MIT.pdf, Honda Loading_202604101.xlsx"),

dict(code="KPI", name="KPI (Krungthai Panich Insurance)", jobtype="CLIENT_KPI_DATA_PROCESSER", folder="Clients/KPI", cls="KPIBatchProcessor",
  files="KPIBatchProcessor.cs, KPIConstants.cs, KPICustomerAttribute.cs, KPICustomerUpdateExcel.cs, KPIEmailTemplate.cs, MultiThreadedCustomerHandlerKPI.cs, CloudFrontSignedUrlGenerator.cs, CustomerProgramDTO.cs, ImportExportHeaderKPI.cs", loc=1731,
  trigger="SFTP pull → S3 → queue row", kind="queue-row",
  pipeline=[
   ("PROD","Scheduler benefit-pull-file-sftp-kpi-data-prod → Lambda benefit-pullfile-sftp-ktc-prod (writes file + PENDING_INSERT row); nightly ≈01:00 UTC","s3://data-processor-sftp/production/clients/kpi/SOS_YYYYMMDD.txt","benefit-import-data-clients-kpi-prod (ENABLED)","benefit-import-prod-job-queue","benefit-kpi-import-prod-job-definitions:13 (by name)","apac-benefit-data-processer-production:20260704.03","PROD"),
   ("PREPROD","pull schedule DISABLED; manual copy","s3://data-processor-sftp/preprod/clients/kpi/","benefit-import-data-clients-kpi-preprod (ENABLED)","benefit-import-preprod-job-queue","benefit-kpi-import-preprod-job-definitions:1 (revision-pinned)","apac-benefit-data-processer-pre-production:20260704.01","PREPROD — DB stopped"),
   ("UAT","manual submit (no rule; test-drop pending)","—","—","benefit-import-uat-job-queue","benefit-kpi-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Daily incremental text file <code>SOS_YYYYMMDD.txt</code>, TIS-620 encoded, 4 columns, CRLF (samples docs/data-processor/SOS_20260303.txt, docs/sample-data/kpi).", reader="The job does NOT use the S3 event payload: it reads the latest <code>customer_import_file_template</code> row WHERE ClientCode='KPI' AND Status='PENDING_INSERT' ORDER BY CreateOn DESC, processes that file and flips it to INSERT_SUCCESS.",
  password="—", uuid="PolicyNumber", mapping="PolicyNo→PolicyNumber, DtPlanStart→EffectiveDate, DtPlanEnd→ExpirationDate, License→LicenseNumber, FileBatch, PlanCode (docs/data-processor/KPI-ConfigDrivenValidation.md)",
  programs="ProgramNumber <code>027782A34501</code> (same both envs).", report="Yes since ABE-5160 (sprint 70).",
  deploy="Prod rule references the job def by name → register a new revision only. Preprod rule pins revision 1.",
  test=["Re-run a specific file: INSERT a PENDING_INSERT row for the FileName, then submit benefit-kpi-import-prod-job-definitions on benefit-import-prod-job-queue overriding RECIPIENT_EMAIL/CC_EMAIL_ADDRESSES. Only ever ONE PENDING_INSERT row at a time.","Uploading to production/clients/kpi/ fires the rule by itself — upload → wait for that job → then insert the row → then submit, or you double-import.","Reconcile against json_extract(CustomerAttributes,'$.PolicyNumber'), never ReferenceID (NULL or a name on some rows)."],
  gotchas=["May 2026 incident: LicenseNumber MaxLength 20 rejected 21-char Thai plates for ~44 daily files; widened to NULL/255; runbook issues/KPI-license-length-reprocess-runbook.md.","Files are incremental — a rejected row is never re-sent; replaying a whole old file overwrites newer data, so build filtered recovery files.","Same latest-row orphan bug as KUC when two files arrive the same day.","409k customer rows — one full scan through the tunnel ≈1 min; LIKE queries on CustomerAttributes take minutes each."],
  open=["Process ALL pending rows, not only the latest."], jira="ABE-5160, epic ABE-5148", docs="AD-KPI - KUC - KTC.pdf, KPI-ConfigDrivenValidation.md"),

dict(code="KTC", name="Krungthai Card Public Co., Ltd. (KTC)", jobtype="CLIENT_KTC_DATA_PROCESSER", folder="Clients/KTC", cls="KTCBatchProcessor",
  files="KTCBatchProcessor.cs, KTCConstants.cs, KTCCustomerAttributeBenefit.cs, KTCHandleFileEncrypt.cs, MultiThreadedCustomerHandler.cs", loc=1194, trigger="SFTP pull → S3 drop", kind="sftp-s3",
  pipeline=[
   ("PROD","Scheduler benefit-pull-file-sftp-ktc-data-prod → Lambda benefit-pullfile-sftp-ktc-prod","s3://aspire-internal-app/production/clients/ktc/","benefit-import-data-clients-ktc-prod (ENABLED)","benefit-import-ktc-prod-job-queue","benefit-ktc-import-prod-job-definition:2 (revision-pinned)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("PREPROD","DISABLED (queue deleted 2026-07 to free a job-queue slot)","s3://aspire-internal-app/preprod/clients/ktc/","benefit-import-data-clients-ktc-preprod (DISABLED, dangling)","— (deleted)","benefit-ktc-import-preprod:7","apac-benefit-data-processer-pre-production","PREPROD"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-ktc-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="PGP-encrypted zip; RPT2 files ≈167 MB (millions of rows).", reader="KTCHandleFileEncrypt decrypts (key from Secrets Manager), then delimited parse; MultiThreadedCustomerHandler.",
  password="PGP key in Secrets Manager (see KTCHandleFileEncrypt)", uuid="From client_customer_field_config", mapping="KTCCustomerAttributeBenefit",
  programs="Five ProgramNumbers by card type: VISA Infinite <code>1310196011</code>, World Mastercard <code>…12</code>, UnionPay Diamond <code>…13</code>, Precious Plus <code>…14</code>, Non-benefit <code>…15</code>. Same in both envs.",
  report="Yes since ABE-5155 (sprint 70); detail lists capped at 200k rows per category (counts stay exact) because of file size.",
  deploy="Prod rule pins revision 2 → register + repoint.",
  test=["UAT manual submit with a small PGP-encrypted sample (needs the UAT PGP key).","Last real file arrived 2025-09 — confirm with the client before assuming the feed is live."],
  gotchas=["SES rule sit-EMAIL-KTC (ktc-prod-import@…) lands in sit/EMAIL/KTC — an old email path unrelated to the current SFTP flow.","benefit-migration-ktc-job-definition-preprod is a one-off migration image, not the processor."],
  open=[], jira="ABE-5155, epic ABE-5148", docs="AD-KPI - KUC - KTC.pdf"),

dict(code="KUC", name="KPI UltraCare (Krungthai Ultra Care Debit Card)", jobtype="CLIENT_KUC_DATA_PROCESSER", folder="Clients/KUC", cls="KUCBatchProcessor",
  files="KUCBatchProcessor.cs, KUCConstant.cs, KUCModel.cs, KUCProcesserFile.cs", loc=1196, trigger="SFTP pull → S3 → queue row", kind="queue-row",
  pipeline=[
   ("PROD","Scheduler benefit-pull-file-sftp-kuc-data-prod → Lambda benefit-pullfile-sftp-ktc-prod; nightly ≈02:30 UTC","s3://data-processor-sftp/production/clients/kuc/KPI_ULTRA_SOS_YYYYMMDD.txt","benefit-import-data-clients-kuc-prod (ENABLED)","benefit-import-prod-job-queue","benefit-kuc-import-prod-job-definitions:12 (by name)","apac-benefit-data-processer-production:v1.4","PROD"),
   ("PREPROD","pull DISABLED","s3://data-processor-sftp/preprod/clients/kuc/","benefit-import-data-clients-kuc-preprod (ENABLED)","benefit-import-preprod-job-queue","benefit-kuc-import-preprod-job-definitions:4 (by name)","apac-benefit-data-processer-pre-production:latest","PREPROD — DB stopped"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-kuc-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Pipe-delimited text, Thai columns TIS-620 (grep needs -a), policies prefixed <code>5U-</code>.", reader="Same latest-PENDING_INSERT-row mechanism as KPI. ReferenceID = bare PolicyNumber.",
  password="—", uuid="PolicyNumber", mapping="KUCModel / field config",
  programs="<strong>Env-specific:</strong> PROD <code>285KUC102687877</code>, UAT <code>888999</code>; constant switches on CONNECTION_TARGET==PROD, overridable by env <code>KUC_PROGRAM_NUMBER</code>. UAT program 595 has Programs.ClientCode = NULL, which is why the old ClientCode lookup attached nothing in UAT.",
  report="Yes since ABE-5158 (sprint 70).", deploy="Rules reference the job def by name → new revision deploys.",
  test=["Re-run: make the target file the latest PENDING_INSERT row, then trigger the job (see KPI).","UAT: manual submit with KUC_PROGRAM_NUMBER unset (defaults to 888999)."],
  gotchas=["Orphan bug: two files for the same day → both rows PENDING_INSERT, only the newest is processed, the older is orphaned forever (2026-06-09: 2,041 records, 1,731 never recovered). Known still-orphaned: row 1166 KPI_ULTRA_SOS_20260312.txt.","Legacy prod ECR naming 'benefit-import-data-kuc-clients-prod' was actually KPI."],
  open=["Process all pending rows."], jira="ABE-5158, epic ABE-5148", docs="AD-KPI - KUC - KTC.pdf"),

dict(code="KXA", name="Krungthai-AXA Life Insurance PCL.", jobtype="CLIENT_KXA_DATA_PROCESSER", folder="Clients/KXA", cls="KXABatchProcessor",
  files="KXABatchProcessor.cs, KXAConstants.cs, KXACustomerAttributes.cs, KXAEmailTemplate.cs, KXAModels.cs, KXAProcessFile.cs", loc=1347, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-KXA ← kxa-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/KXA/","kxa-prod-email-rule (ENABLED)","benefit-import-kxa-prod-job-queue","benefit-kxa-import-prod-job-definitions:4 (revision-pinned)","apac-benefit-data-processer-production:v1.21","PROD"),
   ("UAT","SES uat-EMAIL-KXA ← kxa-uat-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/uat/EMAIL/KXA/","kxa-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-kxa-import-uat-job-definitions:1 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5151-5161-5173-20260909-01","UAT"),
  ],
  fmt="Password-protected xlsx (templates docs/data-processor/KXA_template.xlsx, KXA_test1/2.xlsx); 3 columns.", reader="ExcelOpenHelper.OpenDataSet (env password → Aspire@123 → none).",
  password="env KXA_EXCEL_PASSWORD (default Aspire@123)", uuid="PersonNumber", mapping="PersonNumber, LicenseNumber, EffectiveDate (identical DTO/FieldCode names — new-client convention)",
  programs="ProgramNumber <code>2851121120</code> (program 'Employee Benefit'), client id 96.", report="Yes.",
  deploy="Both rules pin a revision → register + repoint (docs/data-processor/deploy-KXA-infrastructure.md has the full plan).",
  test=["New email to kxa-uat-import@… with KXA_test1.xlsx, or test-drop tool.","Local: KXALocalTest.RunLocalTest()/RunFullTest()/RunProgramTierLookupTest() in Program.cs."],
  gotchas=["KXA was the first client built on the config-driven pattern that TRI/TTR/MSU/TPI/MAZ then cloned."],
  open=[], jira="ABE-5151, ABE-5161, ABE-5173", docs="deploy-KXA-infrastructure.md, KXA_template.xlsx"),

dict(code="MAZ", name="Mazda Sales Thailand (Mazda EV RSA)", jobtype="CLIENT_MAZ_DATA_PROCESSER", folder="Clients/MAZ", cls="MAZBatchProcessor",
  files="MAZBatchProcessor.cs, MAZConstants.cs, MAZCustomerAttributes.cs, MAZEmailTemplate.cs, MAZModels.cs, MAZProcessFile.cs", loc=1087, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-MAZ ← maz-prod-import@aspirelifestylesasia.com (rule added 2026-09-02 — nothing reached prod before)","s3://benefit-raw-email-receiving/prod/EMAIL/MAZ/","maz-prod-email-rule (ENABLED)","benefit-import-prod-job-queue","benefit-maz-import-prod-job-definitions:2 (revision-pinned)","apac-benefit-data-processer-production:v1.21","PROD"),
   ("PREPROD","SES preprod-EMAIL-MAZ ← maz-preprod-import@…","s3://benefit-raw-email-receiving/preprod/EMAIL/MAZ/","maz-preprod-email-rule (ENABLED)","benefit-import-preprod-job-queue","benefit-maz-import-preprod-job-definitions:4 (revision-pinned)","apac-benefit-data-processer-pre-production:v1.21","PREPROD — DB stopped"),
   ("UAT","none","—","—","—","—","—","—"),
  ],
  fmt="Password-protected xlsx.", reader="ExcelOpenHelper.OpenDataSet.", password="env MAZ_EXCEL_PASSWORD (default Aspire@123)", uuid="VINNumber",
  mapping="VINNumber, MPIDate, SaleType, DealerCode, DealerName, CarModel, FirstNameEN",
  programs="PROGRAM_CODE <code>Mazda EV RSA</code> (not yet on ProgramNumber). Onboarding SQL must resolve masterdata by MasterCode (ABE-4838 burn: hardcoded 50203 = 'Golf' in preprod).",
  report="Yes.", deploy="Both rules pin a revision → register + repoint. Remember the SES rule is the 4th leg.",
  test=["Preprod DB is stopped — build a UAT job def + rule if MAZ needs testing (none exists).","Check the customer LIST screen shows the name: MAZ must write FirstNameEN/NameEN/Name core columns as well as the JSON."],
  gotchas=["First MAZ build wrote the name only into CustomerAttributes JSON → blank name in the ABF customer list (list reads the core column, detail reads JSON).","Prod RECIPIENT_EMAIL is the team address with teammates on CC — house pattern, not a bug."],
  open=["UAT pipeline.","Move to ProgramNumber."], jira="ABE-4836, ABE-4838", docs="—"),

dict(code="MBZ", name="Mercedes-Benz (Thailand) Ltd.", jobtype="CLIENT_BENZ_DATA_PROCESSER", folder="Clients/MBZ", cls="MBZBatchProcessor",
  files="MBZBatchProcessor.cs, MBZConstant.cs, MBZModel.cs, MBZProcessFile.cs", loc=1217, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-MBZ ← mercedes-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/MBZ/","mbz-prod-email-rule (ENABLED)","benefit-import-mbz-prod-job-queue","benefit-mbz-import-prod-job-definitions:8 (revision-pinned)","apac-benefit-data-processer-production:mbz-20260603-2","PROD"),
   ("UAT","SES uat-EMAIL-MBZ ← mercedes-uat-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/uat/EMAIL/MBZ/","mbz-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-mbz-import-uat-job-definitions:7 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5149-5150-5154-20260811-04","UAT"),
  ],
  fmt="Excel attachment (xlsx / zipped).", reader="MimeKit → Excel; triggering email since ABE-5149.", password="—", uuid="From client_customer_field_config", mapping="Field config",
  programs="Legacy lookup.", report="Yes (Aug 2026 retrofit).", deploy="Both rules pin a revision → register + repoint.",
  test=["New email to mercedes-uat-import@… or test-drop tool (kind email)."],
  gotchas=["tgr-prod-email-rule / tgr-preprod-email-rule (DISABLED) point at the MBZ job definitions (:1 / :3) — a retired TGR feed reused the Benz processor; do not enable them.","JobType is CLIENT_BENZ_DATA_PROCESSER, not MBZ."],
  open=["Promote the report retrofit to prod (prod image is mbz-20260603-2)."], jira="ABE-5149, ABE-5150, ABE-5154", docs="—"),

dict(code="MIT", name="Mitsubishi Motors", jobtype="CLIENT_MIT_DATA_PROCESSER", folder="Clients/MIT", cls="MITBatchProcessor",
  files="MITBatchProcessor.cs, MITConstants.cs, MITCustomerAttributes.cs, MitsubishiCustomerExcelDTO.cs, CustomerExportDTO.cs, MultiThreadedCustomerHandler.cs", loc=1357, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-Mitsubishi ← mit-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/Mitsubishi/","mitsubishi-prod-email-rule (ENABLED)","benefit-import-mitsubishi-prod-job-queue","benefit-mitsubishi-import-prod-job-definitions:2 (by name)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("UAT","SES uat-EMAIL-MIT ← mit-uat-import@aspirelifestylesasia.com (built 2026-09-08)","s3://benefit-raw-email-receiving/uat/EMAIL/MIT/","mit-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-mit-import-uat-job-definitions:4 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5157-hdr-20260910-01","UAT"),
  ],
  fmt="Excel attachment (MitsubishiCustomerExcelDTO), zipped allowed.", reader="Excel; MultiThreadedCustomerHandler.", password="—", uuid="From client_customer_field_config", mapping="MITCustomerAttributes",
  programs="ProgramNumber <code>285MIT824842</code>, tier <code>MIT</code> → UAT program 594 / tier 1779 (its ProgramCode MIT-CODE-01 deliberately diverges).",
  report="Yes since ABE-5151/5157.", deploy="PROD by name → new revision deploys. UAT rule pins a revision → repoint.",
  test=["New email to mit-uat-import@… or test-drop tool (kind email, folder uat/EMAIL/MIT).","Report visible only on benefit-uat (MIT client 251); SIT has only a test row."],
  gotchas=["Do not confuse with TMI's 'Mitsubishi' sub-template (Tokio Marine) — different client, different mailbox."],
  open=[], jira="ABE-5151, ABE-5157", docs="AD-Honda-TYT-Harley-MIT.pdf"),

dict(code="MSC", name="MSIG Concierge (MSIG Insurance Thailand)", jobtype="CLIENT_MSC_DATA_PROCESSER", folder="Clients/MSC", cls="MSCBatchProcessor",
  files="MSCBatchProcessor.cs, MSCConstants.cs, MSCModels.cs, MSCProcessFile.cs, MSCRowValidator.cs", loc=1199, trigger="SFTP → bridge Lambda → S3 + queue row", kind="queue-row",
  pipeline=[
   ("PROD","Client SFTP s3://sftp-aspirelifestylesasia-com/msig/msig_prod/ → rule msc-msig-sftp-upload-rule → Lambda msc-sftp-bridge-production (inserts PENDING_INSERT row, copies file)","s3://data-processor-sftp/production/clients/msc/","msc-prod-sftp-rule (ENABLED)","benefit-import-prod-job-queue","benefit-msc-import-prod-job-definitions:3 (by name)","apac-benefit-data-processer-production:msc-abe5249-20260813-03","PROD"),
   ("UAT","QA test-drop tool drops file + row (or manual)","s3://data-processor-sftp/uat/clients/msc/","msc-uat-sftp-rule (ENABLED)","benefit-import-uat-job-queue","benefit-msc-import-uat-job-definitions:5 (by name)","apac-benefit-data-processer-pre-production:uat-abe5249-msc-20260813-05","UAT"),
  ],
  fmt="Daily CSV inside a password-protected zip (and/or PGP).", reader="MSCProcessFile; job takes the OLDEST PENDING_INSERT row.", password="env MSC_ZIP_PASSWORD (default in MSCConstants)",
  uuid="PolicyNumber (MaxLength 15 in config)", mapping="InforceAsAt (TEXT, no date validation), Product, PolicyClass, PlanCode, PlanDescription, PolicyNumber, EffectiveDate, ExpirationDate, FirstNameEN, IDCard, Destination — all 11 mandatory",
  programs="ProgramNumber <code>888888</code> — same in both envs (UAT program 896 / tier 2964, PROD program 296).", report="Yes.",
  deploy="Both rules reference the job def by name → register a new revision only. Bridge source + runbook in DataProcesser/infra/msc-sftp-bridge/.",
  test=["Test-drop tool → MSC (writes uat/clients/msc/ + the PENDING_INSERT row; the rule starts the job).","To test the prod bridge without polluting the report, drop a .txt — the rule fires and the Lambda skips on the extension guard."],
  gotchas=["Until 2026-08-14 no bridge existed in prod (pull-file Lambda has hardcoded Chubb/CardX/SCB handlers only) — every daily file stranded. If MSC is ever added to the pull-file Lambda, delete the bridge or files queue twice.","Group policies → one policy legitimately maps to many customers (RISK_NO); compare names + IDCard before calling it a duplicate.","Queue defects (unfixed): pending-row claim is not atomic; one row per run; on failure the EF context is poisoned so the row stays PENDING_INSERT and feeds a double import.","Prod LIST_EMAIL_TO on the job def is still only the developer's address."],
  open=["Set real prod recipients.","Atomic pending-row claim (CSM has the pattern)."], jira="ABE-5249", docs="DataProcesser/infra/msc-sftp-bridge/"),

dict(code="MSH", name="MSIG Home Assistance", jobtype="CLIENT_MSIG_DATA_PROCESSER", folder="Clients/MSH", cls="MSHBatchProcessor",
  files="MSHBatchProcessor.cs, MSHConstant.cs, MSHModel.cs, MSHProcessFile.cs", loc=864, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-MSIGHome ← msighome-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/MSIGHome/","msh-prod-email-rule (ENABLED)","benefit-import-msh-prod-job-queue","benefit-msh-import-prod-job-definitions:6 (by name)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("PREPROD","SES preprod-EMAIL-MSIGHome ← msighome-preprod-import@…","s3://benefit-raw-email-receiving/preprod/EMAIL/MSIGHome/","msh-preprod-email-rule (ENABLED) — targets the PROD queue","benefit-import-msh-prod-job-queue (!)","benefit-msh-import-preprod-job-definitions:7 (by name)","apac-benefit-data-processer-pre-production:latest","PREPROD — DB stopped"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-msh-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Excel attachment (zipped allowed).", reader="Reads the triggering email (GetAttachmentsForThisRun) since ABE-5156; tier matching restricted to the mapped program.", password="—", uuid="From client_customer_field_config", mapping="MSHModel / field config",
  programs="<strong>Env-specific:</strong> PROD <code>285SSC1066385</code> (program 135 with the same number is soft-deleted), UAT <code>285SSC10663851</code>; switch on CONNECTION_TARGET, override env <code>MSH_PROGRAM_NUMBER</code>.",
  report="Yes since ABE-5156 (sprint 70).", deploy="Rules reference by name → new revision deploys.",
  test=["UAT manual submit with an .eml under a UAT prefix (no SES/rule for UAT yet).","Duplicate detection was fixed in the sprint-70 retrofit — send a file with a repeated key and check DuplicateUUID rows."],
  gotchas=["JobType is CLIENT_MSIG_DATA_PROCESSER (shared name with the old MSIG feed).","The preprod rule targets the prod job queue — harmless while the preprod DB is stopped, but wrong."],
  open=["UAT SES rule + EventBridge rule."], jira="ABE-5156, epic ABE-5148", docs="—"),

dict(code="MSU", name="Mitsui Sumitomo Insurance Co., Ltd. Thailand Branch (Roadside / Thai ORIX Leasing file)", jobtype="CLIENT_MSU_DATA_PROCESSER", folder="Clients/MSU", cls="MSUBatchProcessor",
  files="MSUBatchProcessor.cs, MSUConstants.cs, MSUCustomerAttributes.cs, MSUEmailTemplate.cs, MSUModels.cs, MSUProcessFile.cs", loc=1348, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-MSU ← msu-prod-import@aspirelifestylesasia.com (live ≈2026-06-02)","s3://benefit-raw-email-receiving/prod/EMAIL/MSU/","msu-prod-email-rule (ENABLED)","benefit-import-msu-prod-job-queue","benefit-msu-import-prod-job-definitions:5 (revision-pinned)","apac-benefit-data-processer-production:v1.21","PROD"),
   ("PREPROD","SES preprod-EMAIL-MSU","s3://benefit-raw-email-receiving/preprod/EMAIL/MSU/","msu-preprod-email-rule (ENABLED)","benefit-import-msu-preprod-job-queue","benefit-msu-import-preprod-job-definitions:3 (revision-pinned)","apac-benefit-data-processer-pre-production:v1.21","PREPROD — DB stopped"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-msu-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Encrypted xlsx (CDFV2/OLE) '…Aspire_Thai ORIX Leasing (VMI)Report.xlsx', sheet DATA, 17 columns; PolicyNumber like <code>BKD/VEV /25-017884</code> (embedded space preserved). Templates MSU_template.xlsx / MSU_test1.xlsx in docs.",
  reader="ExcelOpenHelper.OpenDataSet.", password="env MSU_EXCEL_PASSWORD (default Aspire@123, no prod override)", uuid="PolicyNumber",
  mapping="PolicyNumber, PolicyType, FirstNameEN, CarBrand, CarModel, CarYear, ChassisNumber, LicenseNumber, CarProvince, EffectiveDate, ExpirationDate, PolicyStatus, ClientCode, MotorCode, TypeBody",
  programs="ProgramNumber <code>2851120762</code> (client id 98). Same both envs.", report="Yes — TMI-contract summary.json (ABE-4839 fixed the processedFailureReason field here).",
  deploy="Prod and preprod rules pin a revision → register + repoint (docs/data-processor/deploy-MSU-infrastructure.md).",
  test=["Decrypt a sample locally with msoffcrypto + Aspire@123.","Presence check: customers.ReferenceID is NULL for MSU — search REPLACE(CustomerAttributes,' ','') LIKE '%BKD/VEV/25-017884%'."],
  gotchas=["'ORIX member data' belongs to MSU, not to TMI's Thai Orix tier.","LicenseNumber (Excel 'Register number') is mandatory in prod config → rows with a blank plate are rejected (472 of 4,742 in the 02-Jun file); unplated leasing vehicles silently go missing.","PolicyStatus has no allowlist — RENEW/NEW both import."],
  open=[], jira="ABE-5178, ABE-4838, ABE-4839", docs="deploy-MSU-infrastructure.md, MSU_template.xlsx"),

dict(code="PBC", name="UOB Private Concierge (voucher codes)", jobtype="CLIENT_PBC_DATA_PROCESSER", folder="Clients/PBC", cls="PBCBatchProcessor",
  files="PBCBatchProcessor.cs, PBCConstants.cs, PBCEmailTemplate.cs, PBCModels.cs, PBCProcessFile.cs, PBCRowValidator.cs, PBCStatusMatrix.cs, PBCTierChange.cs", loc=1457, trigger="Email", kind="email",
  pipeline=[
   ("UAT","SES uat-EMAIL-PBC ← pbc-uat-import@aspirelifestylesasia.com (built 2026-08-10)","s3://benefit-raw-email-receiving/uat/EMAIL/PBC/","pbc-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-pbc-import-uat-job-definitions:7 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5223-api-20260915-02","UAT (from InputTransformer)"),
   ("PROD","not deployed — ABE-5223 was reverted out of the 28 Aug release","—","—","—","—","—","—"),
  ],
  fmt="3-column xlsx: VoucherCode, CustomerTier, Status.", reader="PBCProcessFile + PBCRowValidator + PBCStatusMatrix; tier changes batched per tier (PBCTierChange).", password="env PBC_EXCEL_PASSWORD",
  uuid="VoucherCode", mapping="VoucherCode, CustomerTier, Status — validated against the template only, NOT client_customer_attributes",
  programs="No program mapping — rows are voucher codes. Tier = voucher_codes.CustomerTierId (customers has no tier column); UAT client 483, tiers 3968 Platinum / 4136 PV / 4137 PV+.",
  report="Yes.", deploy="UAT rule pins a revision → repoint. API mode (ABE-5223) logs in with a service account per run and calls the backend with a signed Bearer token for the UAT gateway; re-logins if the token expires mid-run.",
  test=["Smoke test without touching data: mail a 3-column xlsx with made-up codes — every row returns 'Invalid voucher code value.'","UAT has only the Platinum tier configured; a file saying Gold is correctly rejected."],
  gotchas=["Do not merge client_customer_attributes into PBC validation (numeric Status field makes every row fail).","Tier names may be locale JSON ({\"en\":\"Platinum\"}).","Voucher codes match case-sensitively."],
  open=["Prod pipeline + prod release decision."], jira="ABE-5223", docs="—"),

dict(code="SMC", name="SCB CardX (Siam Commercial Bank)", jobtype="CLIENT_SMC_DATA_PROCESSER", folder="Clients/SMC", cls="SMCCardXBatchProcessor",
  files="SMCCardXBatchProcessor.cs, SMCCardXProcessFileFromSFTP.cs, SMCModel.cs, ConstansCardX.cs, CommonSMC.cs, CreateTemplateTest.cs", loc=1391, trigger="SFTP pull → S3 → queue row", kind="queue-row",
  pipeline=[
   ("PROD","Scheduler benefit-production-pullfile-sftp-customer-scb-cardx → Lambda benefit-pullfile-sftp-scb-card-x-production","s3://aspire-internal-app/production/clients/scb-card-x/","benefit-import-data-clients-scb-cardx-production (DISABLED)","benefit-import-scb-cardx-production","benefit-scb-cardx-import-production:5 (by name)","apac-benefit-data-processer-production:v1.5","PROD"),
   ("PREPROD","Scheduler benefit-preprod-pullfile-sftp-customer-scb-cardx (ENABLED) → Lambda …-preprod","s3://aspire-internal-app/preprod/clients/scb-card-x/","benefit-import-data-clients-scb-cardx-preprod (DISABLED)","benefit-import-scb-cardx-pre-prodution-job-queue","benefit-scb-cardx-import-preprod:3 (by name)","benefit-import-data-scbcardx-clients-preprod:latest (legacy own repo)","PREPROD"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-smc-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="PGP-encrypted fixed-width file ≈5 MB.", reader="Decrypt with SMC_DECRYPT_SECRET (Secrets Manager), fixed-width parse; queue-row driven.", password="env SMC_DECRYPT_SECRET (secret name)",
  uuid="From client_customer_field_config", mapping="ConstansCardX",
  programs="Six ProgramNumbers by card: Private Banking <code>1110199501</code>, Platinum Limited <code>…02</code>, First <code>…03</code>, Prime <code>…04</code>, Visa Signature <code>…05</code>, Platinum <code>…06</code>. <strong><code>1110199503</code> is also on BBK program 133 in both envs</strong> — the shared lookup prefers the program owned by the calling client (fe210a3ae).",
  report="Yes since ABE-5159 (sprint 70); detail lists capped at 200k rows per category.",
  deploy="Rules reference by name → new revision deploys. But both S3 rules are DISABLED — SMC is effectively not processing in prod today.",
  test=["UAT manual submit with a small encrypted sample.","Before enabling the prod rule, confirm with the business that the CardX feed should resume."],
  gotchas=["Both EventBridge rules DISABLED while the SFTP pull schedules are ENABLED — files accumulate in S3 unprocessed.","CreateTemplateTest.cs is a test-file generator, not runtime code."],
  open=["Decision on re-enabling the prod rule."], jira="ABE-5159, epic ABE-5148", docs="AD-SCB - SCB CardX - AEON.pdf"),

dict(code="SOR", name="Sompo Insurance", jobtype="CLIENT_SOMPO_DATA_PROCESSER", folder="Clients/SOR", cls="SORBatchProcessor",
  files="SORBatchProcessor.cs, ProcessFileFromSFTP.cs, ConstantSompo.cs, SompoAtttribute.cs, SompoModels.cs", loc=2211, trigger="Scheduled SFTP pull → scheduled Batch", kind="schedule",
  pipeline=[
   ("PROD","Scheduler benefit-data-pullfile-sftp-sompo-client-time-1315-prod / -2115-prod → Lambda apac-benefit-pullfile-sompo-prod; then Scheduler benefit-data-batchjob-insert-file-sompo-client-time-1330-prod / -2130-prod submits the job (13:30 & 21:30 GMT+7)","s3://aspire-internal-app/production/clients/sompo/ (FileProcessed/, FileTransferToClientService/ beneath)","EventBridge Scheduler (by NAME)","sompo-client-import-data-queue-prod","sompo-import-data-client-prod-job-definition:23 (by name)","apac-benefit-data-processer-production:sor-abe5200-20260806","PROD"),
   ("PREPROD","schedules DISABLED","—","—","—","sompo-import-data-client-pre-prod-job-definition:3","apac-benefit-data-processer-pre-production:latest","PREPROD"),
   ("UAT","schedules DISABLED — test-drop tool submits the job","s3://aspire-internal-app/staging/clients/sompo/","—","sompo-client-import-data-queue-uat","sompo-import-data-client-uat-job-definition:5 (by name)","aspire-common-job-uat:latest (OWN repo)","not set — MUST pass CONNECTION_TARGET=UAT"),
  ],
  fmt="PGP-encrypted delimited / Excel files from Sompo SFTP; queue row per file.", reader="ProcessFileFromSFTP.", password="PGP key via Secrets Manager", uuid="From client_customer_field_config", mapping="SompoAtttribute",
  programs="ProgramNumber prefix <code>285A1E1102756</code> (per-plan suffix).", report="Yes.",
  deploy="Scheduler references the job def by NAME → registering a new revision is the deploy; rollback = deregister the newer revisions. UAT: push aspire-common-job-uat:latest (only SOR uses it).",
  test=["Test-drop tool → SOR: writes staging/clients/sompo/ + queue row and submits with CONNECTION_TARGET=UAT.","Never reuse the bare v1.0–v1.6 prod tags — other job defs reference them."],
  gotchas=["UAT job def has no CONNECTION_TARGET → defaults LOCAL and dies on MySQL connect unless overridden.","Only client on its own UAT image repo."],
  open=["Add CONNECTION_TARGET=UAT to the UAT job def."], jira="ABE-5200", docs="—"),

dict(code="TMI", name="Tokio Marine Insurance (sub-templates: RSA/Hongqi, Mitsubishi, Thai Orix)", jobtype="CLIENT_TMI_DATA_PROCESSER", folder="Clients/TMI", cls="TMIBatchProcessor",
  files="TMIBatchProcessor.cs, TMIConstants.cs, TMIEmailTemplate.cs, TMIModels.cs, TMIProcessFile.cs, TmiMitsubishiConstants/Models/ProcessFile.cs, TmiThaiOrixConstants/Models/ProcessFile.cs", loc=3905, trigger="Email → extractor Lambda → S3 landing", kind="email-lambda",
  pipeline=[
   ("PROD","SES aspire-dataprocesser-tmi-prod-emailrule ← tmi-hongqi-prod-import@ / tmi-mitsubishi-prod-import@ / tmi-thaiorix-prod-import@aspirelifestylesasia.com → s3 prod/EMAIL/tmi/ → rule aspire-dataprocessor-tmi-prod-eb-emailattachment → Lambda aspire-dataprocessor-preprod-emailattachment-extractor-lambda (nodejs)","s3://sftp-aspirelifestylesasia-com/tokiomarine/tokiomarine_prod/","aspire-dataprocessor-tmi-prod-eb-filelanding (ENABLED) — passes --bucket/--key CLI args","benefit-import-prod-job-queue","aspire-dataprocessor-tmi-prod-batch-jobqueue:5 (job def, by name)","apac-benefit-data-processer-production:tmi-latest","PROD"),
   ("PREPROD","SES aspire-dataprocesser-tmi-preprod-emailrule (…@aspireasia.net) → preprod/EMAIL/tmi/ → extractor Lambda","s3://sftp-aspirelifestylesasia-com/tokiomarine/tokiomarine_development/","aspire-dataprocessor-tmi-preprod-eb-filelanding (ENABLED)","benefit-import-preprod-job-queue","aspire-dataprocessor-tmi-preprod-batch-jobqueue:6 (by name)","apac-benefit-data-processer-pre-production:tmi-latest","UAT (!) — the preprod job def points at the UAT DB"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-tmi-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Three layouts keyed by mailbox/ProgramNumber: RSA (Hongqi), Mitsubishi, Thai Orix (Excel / text; PGP + zip supported).", reader="Program.cs parses --bucket/--key; TMIProcessFile dispatches to the sub-template reader.", password="—", uuid="Per sub-template", mapping="Per sub-template constants",
  programs="ProgramNumbers <code>2851120063</code> / <code>2851120056</code> / <code>2851120060</code> (one per sub-template, were ProgramCode). Same both envs.",
  report="Yes — TMI is the <strong>reference contract</strong> for summary.json (processedFailureReason).", deploy="Rules reference by name; image tag tmi-latest is mutable — pushing tmi-latest deploys prod immediately. Prefer an immutable tag + new revision.",
  test=["UAT: manual submit with --bucket/--key of a landed file.","Preprod path writes to the UAT DB (CONNECTION_TARGET=UAT on the preprod job def)."],
  gotchas=["Only client using CLI args instead of S3_OBJECT_KEY.","'Thai Orix' here is a TMI tier with chassis-style policies — unrelated to MSU's ORIX leasing file.","tmi-latest mutable tags in prod."],
  open=["Immutable prod tag."], jira="ABE-5177, epic ABE-5148", docs="—"),

dict(code="TPI", name="Thai Paiboon Insurance", jobtype="CLIENT_TPI_DATA_PROCESSER", folder="Clients/TPI", cls="TPIBatchProcessor",
  files="TPIBatchProcessor.cs, TPIConstants.cs, TPICustomerAttributes.cs, TPIEmailTemplate.cs, TPIModels.cs, TPIProcessFile.cs", loc=1306, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-TPI ← tpi-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/TPI/","tpi-prod-email-rule (ENABLED)","benefit-import-prod-job-queue","benefit-tpi-import-prod-job-definitions:4 (revision-pinned)","apac-benefit-data-processer-production:tpi-v1.5","PROD"),
   ("UAT","SES uat-EMAIL-TPI ← tpi-uat-import@aspirelifestylesasia.com (first UAT stack for the shared image, built for ABE-5104)","s3://benefit-raw-email-receiving/uat/EMAIL/TPI/","tpi-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-tpi-import-uat-job-definitions:6 (revision-pinned)","apac-benefit-data-processer-pre-production:tpi-v1.5","UAT"),
  ],
  fmt="Password-protected xlsx, 15 position-based columns; header must match the TPI template or the file is rejected.", reader="ExcelOpenHelper.OpenDataSet; TPILocalTest for DB-free parse+validate.", password="env TPI_EXCEL_PASSWORD",
  uuid="PolicyNumber", mapping="VehicleType, CustomerTitle, FirstNameEN, LastNameEN, PolicyNumber, EffectiveDate, ExpirationDate, Phone, ChassisNumber, LicenseNumber, CarBrand, CarModel, CarYear, PolicyStatus (enum INFORCE/ENDNO/CANCEL), MotorCode",
  programs="PROGRAM_CODE <code>735290-1828622</code> → program 278 / tier 1449 in PROD (client 105; UAT client 470). Not yet on ProgramNumber. Client id resolved from ClientCode at runtime (hardcoded-id bug fixed here first).",
  report="Yes.", deploy="Both rules pin a revision → register + repoint. Tag convention tpi-vX.Y.",
  test=["Local: TPILocalTest.RunLocalTest(TPI_TEST_FILE) in Program.cs.","UAT: new email to tpi-uat-import@… or test-drop tool (kind email)."],
  gotchas=["First client to expose the hardcoded ClientId problem: programs.ClientId == 105 finds nothing on UAT (id 470)."],
  open=["Move to ProgramNumber."], jira="ABE-5104", docs="—"),

dict(code="TRI", name="Triumph Motorcycles (Thailand) Ltd", jobtype="CLIENT_TRI_DATA_PROCESSER", folder="Clients/TRI", cls="TRIBatchProcessor",
  files="TRIBatchProcessor.cs, TRIConstants.cs, TRICustomerAttributes.cs, TRIEmailTemplate.cs, TRIModels.cs, TRIProcessFile.cs", loc=1361, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-TRI ← tri-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/TRI/","tri-prod-email-rule (ENABLED)","benefit-import-tri-prod-job-queue","benefit-tri-import-prod-job-definitions:6 (revision-pinned)","apac-benefit-data-processer-production:tri-20260706-1","PROD"),
   ("PREPROD","SES preprod-EMAIL-TRI","s3://benefit-raw-email-receiving/preprod/EMAIL/TRI/","tri-preprod-email-rule (ENABLED)","benefit-import-tri-preprod-job-queue","benefit-tri-import-preprod-job-definitions:12 (revision-pinned)","apac-benefit-data-processer-pre-production:v1.21","PREPROD — DB stopped"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-tri-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Password-protected xlsx (TRI_template.xlsx / TRI_test1.xlsx in docs).", reader="ExcelOpenHelper.OpenDataSet.", password="env TRI_EXCEL_PASSWORD (default Aspire@123)", uuid="VINNumber",
  mapping="VinNumber→VINNumber, EngineNumber→EngineCode, ModelCode, ModelName→CarModel, BranchName, RegisterDate→EffectiveDate, CustomerName→FirstNameEN, CustomerAddress→AddressEN, CustomerEmail→EmailAddress, CustomerTelephoneNumber→TelephoneNumber, RSAEndDate→ExpirationDate, IsExtend→IsExtended, TotalExtended",
  programs="ProgramNumber <code>2851121116</code> (client id 95) via the shared ProgramTierLookup — TRI carried the helper in ABE-5174.",
  report="Yes — <strong>TRI is the template client</strong> for new email-driven processors (6 files to clone + JobType const + Program.cs case).",
  deploy="Prod and preprod rules pin a revision → register + repoint.",
  test=["Local: TRILocalTest.RunLocalTest()/RunFullTest()/RunProgramTierLookupTest().","UAT: manual submit (no UAT SES rule yet)."],
  gotchas=["Prod RECIPIENT_EMAIL is the team address with teammates on CC — house pattern."],
  open=["UAT SES + rule."], jira="ABE-5174, epic ABE-5148", docs="TRI_template.xlsx"),

dict(code="TTR", name="Toyota Motor Thailand — Roadside service for tire change", jobtype="CLIENT_TTR_DATA_PROCESSER", folder="Clients/TTR", cls="TTRBatchProcessor",
  files="TTRBatchProcessor.cs, TTRConstants.cs, TTRCustomerAttributes.cs, TTREmailTemplate.cs, TTRModels.cs, TTRProcessFile.cs", loc=1328, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-TTR ← ttr-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/TTR/","ttr-prod-email-rule (ENABLED)","benefit-import-ttr-prod-job-queue","benefit-ttr-import-prod-job-definitions:4 (revision-pinned)","apac-benefit-data-processer-production:v1.21","PROD"),
   ("PREPROD","SES preprod-EMAIL-TTR","s3://benefit-raw-email-receiving/preprod/EMAIL/TTR/","ttr-preprod-email-rule (ENABLED)","benefit-import-ttr-preprod-job-queue","benefit-ttr-import-preprod-job-definitions:12 (revision-pinned)","apac-benefit-data-processer-pre-production:v1.21","PREPROD — DB stopped"),
   ("UAT","manual submit (no rule)","—","—","benefit-import-uat-job-queue","benefit-ttr-import-uat-job-definitions:1 (by name)","apac-benefit-data-processer-pre-production:uat-sprint70-20260921-01","UAT"),
  ],
  fmt="Password-protected xlsx (TTR_template.xlsx / TTR_test1.xlsx).", reader="ExcelOpenHelper.OpenDataSet.", password="env TTR_EXCEL_PASSWORD", uuid="ChassisNumber",
  mapping="FirstNameEN, CarBrand, CarModel, CarYear, ChassisNumber, PlateNumber, EffectiveDate, ExpirationDate",
  programs="ProgramNumber <code>2851120730</code> (client id 94).", report="Yes.", deploy="Both rules pin a revision → register + repoint.",
  test=["Local: TTRLocalTest.*","UAT manual submit."], gotchas=["Writes FirstNameEN/NameEN/Name core columns as well as JSON — the reference for the 'name in two places' rule."],
  open=["UAT SES + rule."], jira="ABE-5176, epic ABE-5148", docs="TTR_template.xlsx"),

dict(code="TYT", name="Toyota (Toyota Motor Thailand)", jobtype="CLIENT_TYT_DATA_PROCESSER", folder="Clients/TYT", cls="TYTBatchProcessor",
  files="TYTBatchProcessor.cs, TYTConstants.cs, TYTAttribute.cs, TYTEmailTemplate.cs, TYTModels.cs, TYTProcessFile.cs", loc=1697, trigger="Email", kind="email",
  pipeline=[
   ("PROD","SES prod-EMAIL-Toyota ← toyota-prod-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/prod/EMAIL/Toyota/","toyota-prod-email-rule (ENABLED)","benefit-import-toyota-prod-job-queue","benefit-toyota-import-prod-job-definitions:2 (revision-pinned)","apac-benefit-data-processer-production:v1.0","PROD"),
   ("UAT","SES uat-EMAIL-Toyota ← toyota-uat-import@aspirelifestylesasia.com","s3://benefit-raw-email-receiving/uat/EMAIL/Toyota/","tyt-uat-email-rule (ENABLED)","benefit-import-uat-job-queue","benefit-tyt-import-uat-job-definitions:2 (revision-pinned)","apac-benefit-data-processer-pre-production:uat-abe5161-hdr-20260910-01","UAT"),
  ],
  fmt="Excel 'Toyota-Format' xlsx (Toyota-Format.xlsx / Toyota-Format2.xlsx in docs).", reader="TYTProcessFile; config-driven validation (docs/data-processor/TYT-ConfigDrivenValidation.md).", password="—", uuid="ChassisNumber",
  mapping="ChassisNo→ChassisNumber, CustomerName, RoadsideStartDate→EffectiveDate, EndofCampaign→ExpirationDate, Vendor, Project, TotalNo, Model→CarModel, Specification, EngineNo→CarEngineNumber, ModelDescription, LicencePlate→PlateNumber, TotalYear, SOSNumber (legacy DTO names kept, FieldCodes renamed)",
  programs="ProgramNumber <code>TYT-03AYCR000011</code> (client id 376).", report="Yes — TYT was the first legacy processor retrofitted with the report and is the diff reference for the sprint-70 retrofits.",
  deploy="Both rules pin a revision → register + repoint (docs/data-processor/deploy-TYT-production.md).",
  test=["New email to toyota-uat-import@… or test-drop tool.","Local: TYTLocalTest.SetEnvironmentVariables()/SeedTestData()."],
  gotchas=["Prod image is still v1.0 — the report build (uat-abe5161-hdr) is UAT-only."],
  open=["Promote the report build to prod."], jira="ABE-5161", docs="deploy-TYT-production.md, TYT-ConfigDrivenValidation.md, Toyota-Format.xlsx"),
]
